spring:
  datasource:
    dynamic:
      primary: shop #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        shop:
          url: jdbc:mysql://rm-2ze7b0favk212d188mo.mysql.rds.aliyuncs.com:3306/aiuskinshop
          username: aiuskinshop
          password: Aiguangjie02
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        z2025:
          url: jdbc:mysql://rm-2ze7b0favk212d188mo.mysql.rds.aliyuncs.com:3306/2025
          username: aiuskinshop
          password: Aiguangjie02
          driver-class-name: com.mysql.jdbc.Driver
        copy:
          url: jdbc:mysql://rm-2ze7b0favk212d188mo.mysql.rds.aliyuncs.com:3306/aiuskincopy
          username: aiuskinshop
          password: Aiguangjie02
          driver-class-name: com.mysql.jdbc.Driver
